alias: EcoFlow PS Power Adj
description: >-
  Автоматически каждые 3 сек коректирует размер потребления квартиры для
  PowerStream на основе данных из Tyua Automat (Local)
trigger:
  - platform: time_pattern
    seconds: /3
condition:
  - condition: sun
    after: sunrise
  - condition: time
    before: "14:00:00"
action:
  - service: pyscript.set_ef_powerstream_custom_load_power
    data:
      SerialNumber: SerialNumber
      TotalPower: >-
        {% set total_power = (states('sensor.tyuaswichpower') | float(0) +
        states('sensor.powerstream_inverter_output_watts') | float(0) - 2) %} 
        {% set total_solar = (states('sensor.powerstream_solar_1_watts') |
        float(0) + states('sensor.powerstream_solar_2_watts') | float(0)) %}  {%
        set total_power_final = [total_power, total_solar] | min | round %}  {{
        total_power_final }}
      NotWorking: >-
        {% set total_volt =
        [states('sensor.powerstream_solar_1_input_potential') | float(0), 
        states('sensor.powerstream_solar_2_input_potential') | float(0)] | max
        %}  {% if total_volt > 21 and total_solar < 1 %}
          true
        {% else %}
          false
        {% endif %}
      TheSame: |-
        {% if total_power_final == 'sensor.powerstream_other_loads' %}
          true
        {% else %}
          false
        {% endif %}
mode: single
